### ISSUE TITLE
Running example throws java exception.

### ISSUE THREAD

**Issue by jameskyle** [sequenceiq/docker-spark#1]
Running the suggested example: 
./bin/spark-shell --master yarn-client --driver-memory 1g --executor-memory 1g --executor-cores 1

Throws the following java exception:

```
java.net.ConnectException: Call From sandbox/172.16.0.6 to localhost:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
```

Running the subsequent command produces the following:

```
scala> sc.parallelize(1 to 1000).count()
<console>:11: error: not found: value sc
               sc.parallelize(1 to 1000).count()
               ^
```

**Comment by alistair-broomhead** [comment]
I am getting this issue with `sequenceiq/spark:1.3.0` My kernel version is `Linux al-XPS-13-mint 3.19.3-031903-generic` - can anyone confirm whether this is a regression, or whether there is a new issue with a similar profile?
