### ISSUE TITLE
Can we get the latest version of Spark (1.2) on Ubuntu?

### ISSUE THREAD

**Issue by nealmcb** [sequenceiq/docker-spark#12]
Thanks again for these images!

I'm astonished to learn that CentOS 6.5 (used in the latest Spark 1.2.0 tag at https://registry.hub.docker.com/u/sequenceiq/spark/tags/manage/) apparently remains in the dark ages of Python, since it has Python version 2.6, and it seems that upgrading to 2.7 breaks the yum installer.  That means that the best way to run python (ipython notebook) only works with a version that is years out of date, and is painful to install:

 Big Mac data: Pain in the culo setting up IPython Centos 6.5
  http://bigmacdata.blogspot.com/2015/01/pain-in-culo-setting-up-ipython-centos.html

So I'd once again love to see an Ubuntu build of Spark 1.2.0. (like with https://github.com/sequenceiq/hadoop-docker/issues/16).

Thanks!

**Comment by matyix** [comment]
Hi @nealmcb 

Just made one on Ubuntu using Hadoop 2.6.0 and Spark 1.2.0. Tested locally and pushed to Docker.io for an official build. You should be able to pull it in a few minutes (once Docker.io finished the build).

Meanwhile you can check the [branch](https://github.com/sequenceiq/docker-spark/tree/v1.2.0onHadoop2.6.0-ubuntu).

**Comment by nealmcb** [comment]
Awesome - thank you!
