### ISSUE TITLE
stateful python streaming examples fail

### ISSUE THREAD

**Issue by mhowsden** [sequenceiq/docker-spark#17]
Thanks so much for doing this, this docker has come in handy getting me going with spark.

I tried the streaming examples with 

    spark-submit /usr/local/spark/examples/src/main/python/streaming/network_wordcount.py 172.17.42.1 9999 2> out.txt

And it works great but when I run

    spark-submit /usr/local/spark/examples/src/main/python/streaming/stateful_network_wordcount.py 172.17.42.1 9999 2> out.txt

I don't get any results and the errors I get are

    15/03/16 20:09:23 ERROR scheduler.JobScheduler: Error running job streaming job 1426550835000 ms.0
    py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: null
        at py4j.Protocol.getReturnValue(Protocol.java:417)
    --
    15/03/16 20:09:23 ERROR scheduler.JobScheduler: Error running job streaming job  1426550836000 ms.0
    py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: null
        at py4j.Protocol.getReturnValue(Protocol.java:417)
    --
    15/03/16 20:09:23 ERROR scheduler.JobScheduler: Error running job streaming job 1426550837000 ms.0
    py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: null
        at py4j.Protocol.getReturnValue(Protocol.java:417)
    --
    15/03/16 20:09:23 ERROR scheduler.JobScheduler: Error running job streaming job 1426550838000 ms.0
    py4j.Py4JException: Error while obtaining a new communication channel
        at py4j.CallbackClient.getConnectionLock(CallbackClient.java:155)
    --
    15/03/16 20:09:23 ERROR scheduler.JobScheduler: Error running job streaming job 1426550839000 ms.0
    py4j.Py4JException: Error while obtaining a new communication channel
        at py4j.CallbackClient.getConnectionLock(CallbackClient.java:155)
    --
    15/03/16 20:09:23 ERROR scheduler.JobScheduler: Error running job streaming job 1426550840000 ms.0
    py4j.Py4JException: Error while obtaining a new communication channel
        at py4j.CallbackClient.getConnectionLock(CallbackClient.java:155)

Apologies if this is just a misunderstanding of how I need to run this in the context of docker or a simple flag I need to add to the spark-submit command.  I'm new to spark (and docker) and I'm unclear about what's failing.  The recoverable_network_wordcount.py failed as well.

**Comment by blbradley** [comment]
I think this is a problem with Spark. I'm having this same error happen. Did you ever fix your issue?

**Comment by PhucNoel** [comment]
I have the same problem too.

**Comment by mhowsden** [comment]
I never fixed this issue but I did reproduce it without docker so it's a problem with Spark, probably doesn't belong here.

**Comment by vishnevski** [comment]
Spark streaming needs at least two threads on the worker/slave side.
It works like: ./bin/spark-submit --master local[2]  examples/src/main/python/streaming/network_wordcount.py 127.0.0.1 9999 
Found here http://comments.gmane.org/gmane.comp.lang.scala.spark.user/14543
