### ISSUE TITLE
Hadoop “Unable to load native-hadoop library for your platform” error

### ISSUE THREAD

**Issue by NanXiao** [sequenceiq/docker-spark#21]
I have put this issue is from [SO](http://stackoverflow.com/questions/30369380/hadoop-unable-to-load-native-hadoop-library-for-your-platform-error-on-docker), but nobody answer it, so I hope i can get answer here, thanks!

I am using docker-spark 1.3.0. After starting `spark-shell`, it outputs:  

    15/05/21 04:28:22 DEBUG NativeCodeLoader: Failed to load native-hadoop with error: java.lang.UnsatisfiedLinkError:no hadoop in java.library.path
    15/05/21 04:28:22 DEBUG NativeCodeLoader: java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib

The environment variables of this `spark container` are:  

	bash-4.1# export
	declare -x BOOTSTRAP="/etc/bootstrap.sh"
	declare -x HADOOP_COMMON_HOME="/usr/local/hadoop"
	declare -x HADOOP_CONF_DIR="/usr/local/hadoop/etc/hadoop"
	declare -x HADOOP_HDFS_HOME="/usr/local/hadoop"
	declare -x HADOOP_MAPRED_HOME="/usr/local/hadoop"
	declare -x HADOOP_PREFIX="/usr/local/hadoop"
	declare -x HADOOP_YARN_HOME="/usr/local/hadoop"
	declare -x HOME="/"
	declare -x HOSTNAME="sandbox"
	declare -x JAVA_HOME="/usr/java/default"
	declare -x OLDPWD
	declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/usr/local/spark/bin:/usr/local/hadoop/bin"
	declare -x PWD="/"
	declare -x SHLVL="3"
	declare -x SPARK_HOME="/usr/local/spark"
	declare -x SPARK_JAR="hdfs:///spark/spark-assembly-1.3.0-hadoop2.4.0.jar"
	declare -x TERM="xterm"
	declare -x YARN_CONF_DIR="/usr/local/hadoop/etc/hadoop"

After referring [Hadoop “Unable to load native-hadoop library for your platform” error on CentOS](http://stackoverflow.com/questions/19943766/hadoop-unable-to-load-native-hadoop-library-for-your-platform-error-on-centos), I have done the following:  

(1) Check the `hadoop` library:  

    bash-4.1# file /usr/local/hadoop/lib/native/libhadoop.so.1.1.0
    /usr/local/hadoop/lib/native/libhadoop.so.1.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped

Yes, it is `64-bit` library.

(2) Try adding the `HADOOP_OPTS` environment variable:  

    export HADOOP_OPTS="$HADOOP_OPTS -Djava.library.path=/usr/local/hadoop/lib/native"

It doesn't work, and reports the same error.

(3) Try adding the `HADOOP_OPTS` and `HADOOP_COMMON_LIB_NATIVE_DIR` environment variable:  

    export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
    export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib"

It still doesn't work, and reports the same error.

Could anyone give some clues about the issue?

**Comment by NanXiao** [comment]
Adding the `Hadoop` library into `LD_LIBRARY_PATH` fix this problem:  

    export LD_LIBRARY_PATH=/usr/local/hadoop/lib/native/:$LD_LIBRARY_PATH

**Comment by jzhuge** [comment]
You can also use **spark.executor.extraLibraryPath** and/or **spark.driver.extraLibraryPath**.
