### ISSUE TITLE
Is there an ETA on a sequenceiq/spark:1.3.1 image?

### ISSUE THREAD

**Issue by alistair-broomhead** [sequenceiq/docker-spark#22]
Currently we have tests run in a docker container failing due to use of features in 1.3.1, which is the version live on EMR - it would be great to have the same version of spark in a docker image as we have in our live environment

**Comment by oleewere** [comment]
Hi @alistair-broomhead 

Just made the ubuntu and centos image using Spark 1.3.1. Now, you should be able to pull it. (sequenceiq/spark:1.3.1 and sequenceiq/spark:1.3.1-ubuntu)

Oliver

**Comment by alistair-broomhead** [comment]
Hmm - currently having no joy:
```
Step 0 : FROM sequenceiq/spark:1.3.1
Pulling repository sequenceiq/spark
time="2015-06-04T08:57:21Z" level="info" msg="Tag 1.3.1 not found in repository sequenceiq/spark" 
```

**Comment by oleewere** [comment]
Hi @alistair-broomhead,
You were right, 1.3.1 tag was missing, just ubuntu one was there. Now the centos image is available. Thanks for your feedback. 

Oliver

**Comment by alistair-broomhead** [comment]
@oleewere yay that worked!
```
Sending build context to Docker daemon 
Step 0 : FROM sequenceiq/spark:1.3.1
Pulling repository sequenceiq/spark
440d8015808a: Pulling image (1.3.1) from sequenceiq/spark
440d8015808a: Pulling image (1.3.1) from sequenceiq/spark, endpoint: https://registry-1.docker.io/v1/
440d8015808a: Pulling dependent layers
...
```
