### ISSUE TITLE
Can't install packages

### ISSUE THREAD

**Issue by gone-phishing** [sequenceiq/docker-spark#23]
1. ```sudo docker run -i -t sequenceiq/spark:latest /bin/bash```
2. ```uname -a ``` : 
    Linux xxx 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
 
This implies the image is built from an Ububtu image. But when in the Dockerfile I use this:
```RUN apt-get update```
It says ```apt-get : command not found```

Where am I going wrong ? I need to install a lot of packages using this. What's the workaround ?

**Comment by biharitomi** [comment]
Hi,

The result of your second step is really strange.
If you check the docker file of docker spark it's base docker image is 'sequenceiq/hadoop-docker:2.6.0' and that image is based on centos-6.5 as you can see here:
https://github.com/sequenceiq/hadoop-docker/blob/2.6.0/Dockerfile#L5

Br,
Tamas

**Comment by gone-phishing** [comment]
Hi,

I know that's unexpected, and I can also find yum package installer in the bin folder but then why is uname -a giving Ubuntu as an output.
Also, do we have any ubuntu based image for spark?

Thanks,
Ritesh

**Comment by biharitomi** [comment]
Hi,

I do not know what cause that problem, but that image should be Centos based. If you would like to use an Ubuntu based, please use the image with tag: '**sequenceiq/spark:1.3.0-ubuntu**'
You can check the type/version of distro with 'cat /etc/issue' command on that image too.

Br,
Tamas

**Comment by gone-phishing** [comment]
Hi,

The ubuntu one is not available I guess. I got this error : 
```INFO[1632] Error pulling image (1.3.0-ubuntu) from sequenceiq/spark, Server error: Status 504 while fetching image layer (f3dbf1b259ad6ef6b01019c6e0ff6d7a1e69a7e1bb0a942b3197ee8d2da39acc) ```

Something wrong with the servers? Can you try pulling one for yourself and see if you can fix it ? It'll be really great help. 
P.S. : You should definitely look into the CentOS/ Ubuntu error. Can cause confusion amongst other users too ?

**Comment by gone-phishing** [comment]
Hey , 
It's working now. I am able to download the image and its currently installing maven in it. Thanks for the help :)

**Comment by biharitomi** [comment]
Hi,

I tried to investigate what was the original problem of this thread and when the `uname -a` command is executed that returns with the host OS name as you can see in the following example where I get '*tinycore*' as result because on OSX the boot2docker runs a tinycore linux to provision the docker containers.
```shell
 docker run -i -t sequenceiq/spark:latest /bin/bash
bash-4.1# uname -a
Linux 31953a7b04f4 3.18.11-tinycore64 #1 SMP Thu Apr 16 17:46:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

bash-4.1# cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m
```
So if you would like to get the type of os in a docker container please use `cat /etc/issue` command if it is possible.

Br,
Tamas

**Comment by gone-phishing** [comment]
Yes, I guess whenever we launch a container in interactive mode using ```-i -t``` flag, it performs all shell operations with help of host OS kernel and stores them as json objects and finally reads from them to display output. It uses just the kernel not the filesystem as then packages existing only on the image gets executed and not the packages on the host OS. At least that's how I think docker works. 
Anyways, Thanks for clarifying my doubt :)
