### ISSUE TITLE
Add TAG 1.4.0

### ISSUE THREAD

**Issue by igorbarinov** [sequenceiq/docker-spark#28]
https://registry.hub.docker.com/u/sequenceiq/spark/tags/manage/
```
vagrant@ubuntu-14:~$ docker run -d -h sandbox sequenceiq/spark:1.4.0 -d
Unable to find image 'sequenceiq/spark:1.4.0' locally
Pulling repository sequenceiq/spark
Tag 1.4.0 not found in repository sequenceiq/spark
```

**Comment by igorbarinov** [comment]
```
vagrant@ubuntu-14:~/docker-spark$ docker build .
Sending build context to Docker daemon 179.7 kB
Sending build context to Docker daemon
Step 0 : FROM sequenceiq/hadoop-docker:2.6.0
Pulling repository sequenceiq/hadoop-docker
Get https://index.docker.io/v1/repositories/sequenceiq/hadoop-docker/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: too many redirects
```
how to fix it?

**Comment by matyix** [comment]
You can build the image for yourself - no need to pull it from the Docker repository. Regarding the second - it's related to your Docker/host network config, has nothing to do with the image.
Not sure what is your environment (thus can't give you hints) but there is plenty of documentation available for this issue.

**Comment by igorbarinov** [comment]
I know I can build image myself. In in your readme there is a command: **docker pull sequenceiq/spark:1.4.0** and it doesn't work because you don't have this tag. I think you should change readme or post 1.4.0 tag. Thanks!

My problem with DNS solved after I added to /etc/resolv.conf google dns servers
nameserver 8.8.8.8
nameserver 8.8.4.4

vagrant dns is not very stable
