### ISSUE TITLE
Spark_v1.3.0-ubuntu with scala_v2.11.4

### ISSUE THREAD

**Issue by gone-phishing** [sequenceiq/docker-spark#29]
I'm currently using the spark:1.3.0-ubuntu image built against scala_2.10.4
Can we please have the same image built against scala_2.11.4 as we are facing dependency failure issues.

**Comment by matyix** [comment]
This is the default version coming with the Spark release - it's the usual Scala dependency hell ... the Dockerfile and the whole project is open source, there are instructions of how to built the image, so I guess you can add whatever Scala version you want. 

If we divert from the default that others will complain - that's the whole point of open source, you can fork the repository and add your change and build the image. The whole change should not take more than 5 minutes ...

**Comment by gone-phishing** [comment]
@matyix The spark 1.3.0 page lists building instructions for scala 2.11.4 which is basically adding a
 -Dscala 2.11.4 part to the mvn build command. So it shouldn't take long for sure. I'll be happy to contribute if you can help me on how to proceed.
