### ISSUE TITLE
sparkR command does not work

### ISSUE THREAD

**Issue by teramonagi** [sequenceiq/docker-spark#31]
I downloaded docker-spark images via docker pull command and run it with
```bash
docker run -it sequenceiq/spark:1.4.0 bash
```

After that, I found "sparkR" was already in `/usr/local/spark/bin`.
I wanted to try it ant got the following result:
```bash
bash-4.1# sparkR
env: R: No such file or directory
```

It seems that we have to write "install R" like commands in docker file.
Do you have any plan to install R in this docker image in the near future?
(Is it possible for me to write that and make a PR to this rpeository?)

**Comment by akanto** [comment]
Thanks for the fix.

**Comment by neeraj-garg5** [comment]
Hi,
I've been facing the same issue i.e. while trying to run the command ./bin/sparkR it gives me the error:
env: R: No such file or directory

Could you please help to resolve the issue.

Regards,
Neeraj
