### ISSUE TITLE
Tag 1.5.1 not found in repository docker.io/sequenceiq/spark

### ISSUE THREAD

**Issue by rwrnet** [sequenceiq/docker-spark#37]
Hi Guys,

love that image. Why don't you update docker hub? Readme implies that there is recent version.

For the moment being, I cloned the repo and built it myself. But hub is more comfortable. :)

Thanks for the great image. :)

**Comment by jconlon** [comment]
Same problem.  Please update docker hub with 1.5.1 to conform with your ReadMe instructions.  

thanks

**Comment by martonsereg** [comment]
Hi, I've updated docker hub with 1.5.1, it should work now.
