### ISSUE TITLE
Container terminates after 1-2 minutes

### ISSUE THREAD

**Issue by denniskl** [sequenceiq/docker-spark#43]
Hi, 

my container (*) always terminates after a couple of minutes:

Is this expected? Do you have further information how to debug it?

CONTAINER ID        IMAGE                    COMMAND               CREATED             STATUS                     PORTS               NAMES
e3e36cf709bf        sequenceiq/spark:1.5.1   "/etc/bootstrap.sh"   2 minutes ago       Exited (0) 5 seconds ago                       elated_jones

Many thanks for help,
Dennis

(*)
docker run -d -h sandbox sequenceiq/spark:1.5.1

**Comment by leninmehedy** [comment]
same here. It stops with the log below:

```
docker run sequenceiq/spark:1.6.0 bash
/
Starting sshd: [  OK  ]
Starting namenodes on [1d3ba84b866f]
1d3ba84b866f: starting namenode, logging to /usr/local/hadoop/logs/hadoop-root-namenode-1d3ba84b866f.out
localhost: starting datanode, logging to /usr/local/hadoop/logs/hadoop-root-datanode-1d3ba84b866f.out
Starting secondary namenodes [0.0.0.0]
0.0.0.0: starting secondarynamenode, logging to /usr/local/hadoop/logs/hadoop-root-secondarynamenode-1d3ba84b866f.out
starting yarn daemons
starting resourcemanager, logging to /usr/local/hadoop/logs/yarn--resourcemanager-1d3ba84b866f.out
localhost: starting nodemanager, logging to /usr/local/hadoop/logs/yarn-root-nodemanager-1d3ba84b866f.out
```

**Comment by denniskl** [comment]
Hi, 

do you have some ideas?


Many thanks for help,

Dennis

**Comment by martonsereg** [comment]
Hi, my guess is that you're missing an additional `-d` switch from your docker run command. Instead of typing
`docker run -d -h sandbox sequenceiq/spark:1.5.1`
try
`docker run -d -h sandbox sequenceiq/spark:1.5.1 -d`
The first `-d` is passed to the docker daemon, the second `-d` is passed to the entrypoint script.
