### ISSUE TITLE
run on multiple machines?

### ISSUE THREAD

**Issue by joshjdevl** [sequenceiq/docker-spark#9]
How do I run this on multiple machines?

**Comment by matyix** [comment]
Theoretically should work as the base Hadoop container is used by [others](https://issues.apache.org/jira/browse/YARN-1964) in a cluster - we will make a blog post about guiding you through this - however when we use Spark we either provision a `multinode` cluster with our Apache Ambari docker [container](http://blog.sequenceiq.com/blog/2014/12/04/multinode-ambari-1-7-0/) (use the multi-node-yarn blueprint) or [Cloudbreak](http://sequenceiq.com/cloudbreak/).
